---
arch: amd64
versions:
  kubernetes: 1.31.1
  containerd: 1.7.22
  cni: 1.5.1
  etcd: 3.5.16
  runc: 1.1.15
  crictl: 1.31.1
domain: kubernetes.local
jumpbox:
  hostname: jumpbox
  ip: 192.168.56.10
  memory: 512
server:
  hostname: server
  ip: 192.168.56.20
  memory: 2048
nodes:
  node0:
    hostname: node-0
    ip: 192.168.56.100
    memory: 2048
    subnet: 10.200.0.0/24
  node1:
    hostname: node-1
    ip: 192.168.56.101
    memory: 2048
    subnet: 10.200.1.0/24
